// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: message_proto/messages.proto

package messages_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	// Unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	// Server Streaming
	PrimeLister(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (CalculatorService_PrimeListerClient, error)
	// Client Streaming
	AverageCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_AverageCalculatorClient, error)
	// Bidirectional Streaming
	MaxCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_MaxCalculatorClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeLister(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (CalculatorService_PrimeListerClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], "/calculator.CalculatorService/PrimeLister", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeListerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeListerClient interface {
	Recv() (*PrimeResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeListerClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeListerClient) Recv() (*PrimeResponse, error) {
	m := new(PrimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) AverageCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_AverageCalculatorClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], "/calculator.CalculatorService/AverageCalculator", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceAverageCalculatorClient{stream}
	return x, nil
}

type CalculatorService_AverageCalculatorClient interface {
	Send(*AverageRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type calculatorServiceAverageCalculatorClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceAverageCalculatorClient) Send(m *AverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceAverageCalculatorClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) MaxCalculator(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_MaxCalculatorClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], "/calculator.CalculatorService/MaxCalculator", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceMaxCalculatorClient{stream}
	return x, nil
}

type CalculatorService_MaxCalculatorClient interface {
	Send(*MaxRequest) error
	Recv() (*MaxResponse, error)
	grpc.ClientStream
}

type calculatorServiceMaxCalculatorClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceMaxCalculatorClient) Send(m *MaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceMaxCalculatorClient) Recv() (*MaxResponse, error) {
	m := new(MaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility
type CalculatorServiceServer interface {
	// Unary
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	// Server Streaming
	PrimeLister(*PrimeRequest, CalculatorService_PrimeListerServer) error
	// Client Streaming
	AverageCalculator(CalculatorService_AverageCalculatorServer) error
	// Bidirectional Streaming
	MaxCalculator(CalculatorService_MaxCalculatorServer) error
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (UnimplementedCalculatorServiceServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServiceServer) PrimeLister(*PrimeRequest, CalculatorService_PrimeListerServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeLister not implemented")
}
func (UnimplementedCalculatorServiceServer) AverageCalculator(CalculatorService_AverageCalculatorServer) error {
	return status.Errorf(codes.Unimplemented, "method AverageCalculator not implemented")
}
func (UnimplementedCalculatorServiceServer) MaxCalculator(CalculatorService_MaxCalculatorServer) error {
	return status.Errorf(codes.Unimplemented, "method MaxCalculator not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeLister_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeLister(m, &calculatorServicePrimeListerServer{stream})
}

type CalculatorService_PrimeListerServer interface {
	Send(*PrimeResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeListerServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeListerServer) Send(m *PrimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_AverageCalculator_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).AverageCalculator(&calculatorServiceAverageCalculatorServer{stream})
}

type CalculatorService_AverageCalculatorServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*AverageRequest, error)
	grpc.ServerStream
}

type calculatorServiceAverageCalculatorServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceAverageCalculatorServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceAverageCalculatorServer) Recv() (*AverageRequest, error) {
	m := new(AverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_MaxCalculator_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).MaxCalculator(&calculatorServiceMaxCalculatorServer{stream})
}

type CalculatorService_MaxCalculatorServer interface {
	Send(*MaxResponse) error
	Recv() (*MaxRequest, error)
	grpc.ServerStream
}

type calculatorServiceMaxCalculatorServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceMaxCalculatorServer) Send(m *MaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceMaxCalculatorServer) Recv() (*MaxRequest, error) {
	m := new(MaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeLister",
			Handler:       _CalculatorService_PrimeLister_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AverageCalculator",
			Handler:       _CalculatorService_AverageCalculator_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MaxCalculator",
			Handler:       _CalculatorService_MaxCalculator_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message_proto/messages.proto",
}
